// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `init_schema`, `open_connection`, `sqlite_path`, `write_index_value_to_sqlite`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

Future<void> migrateIndexJsonToSqlite({required String indexPath}) =>
    RustLib.instance.api
        .crateApiLibraryDbMigrateIndexJsonToSqlite(indexPath: indexPath);

Future<List<IndexFolder>> readIndexFromSqlite({required String indexPath}) =>
    RustLib.instance.api
        .crateApiLibraryDbReadIndexFromSqlite(indexPath: indexPath);

class IndexAudio {
  final String title;
  final String artist;
  final String album;
  final String? albumArtist;
  final int track;
  final BigInt duration;
  final int? bitrate;
  final int? sampleRate;
  final String path;
  final BigInt modified;
  final BigInt created;
  final String? by;

  const IndexAudio({
    required this.title,
    required this.artist,
    required this.album,
    this.albumArtist,
    required this.track,
    required this.duration,
    this.bitrate,
    this.sampleRate,
    required this.path,
    required this.modified,
    required this.created,
    this.by,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      albumArtist.hashCode ^
      track.hashCode ^
      duration.hashCode ^
      bitrate.hashCode ^
      sampleRate.hashCode ^
      path.hashCode ^
      modified.hashCode ^
      created.hashCode ^
      by.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IndexAudio &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          albumArtist == other.albumArtist &&
          track == other.track &&
          duration == other.duration &&
          bitrate == other.bitrate &&
          sampleRate == other.sampleRate &&
          path == other.path &&
          modified == other.modified &&
          created == other.created &&
          by == other.by;
}

class IndexFolder {
  final String path;
  final BigInt modified;
  final BigInt latest;
  final List<IndexAudio> audios;

  const IndexFolder({
    required this.path,
    required this.modified,
    required this.latest,
    required this.audios,
  });

  @override
  int get hashCode =>
      path.hashCode ^ modified.hashCode ^ latest.hashCode ^ audios.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IndexFolder &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          modified == other.modified &&
          latest == other.latest &&
          audios == other.audios;
}
