// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<double> systemVolumeInit() =>
    RustLib.instance.api.crateApiSystemVolumeSystemVolumeInit();

void systemVolumeSet({required double val}) =>
    RustLib.instance.api.crateApiSystemVolumeSystemVolumeSet(val: val);

double systemVolumeGet() =>
    RustLib.instance.api.crateApiSystemVolumeSystemVolumeGet();

void systemVolumeDispose() =>
    RustLib.instance.api.crateApiSystemVolumeSystemVolumeDispose();
